### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by Narayanna** [Lord-Zedd/MCCLocalizationEditor#1]
Hello, with the new update to the game, subtitles have been added to all games.
It extracts all the language files without any problems, but when trying to export the language files of only 2 games, the program crashes.
Crashes on EN_HaloReach.bin and EN_Halo2A.bin.
Can you make a correction please?

These are the language files of all games belonging to the game.
https://www.mediafire.com/file/hduthmwv1h00nu5/Halo.rar

**Comment by kecox42069** [comment]
1.0a works for me

**Comment by Lord-Zedd** [comment]
I can't reproduce with 1.0a but I notice the main repo page was offering an the original 1.0 as latest which did have XML bugs, so I switched that around. Double check you are on 1.0a and try again.

**Comment by Narayanna** [comment]
Yes, 1.0a works much more stable, it removed all of them without any problem. Thank you so much.
I want to ask one last thing.
Is it possible to extract it in csv format instead of xml? Editing text in XML is much more difficult. Or with which tool can I edit the text file easily?

**Comment by Lord-Zedd** [comment]
They could be exported to any format but XML seemed like the easiest choice to me. Notepad++ is a good editor for XML.

**Comment by Narayanna** [comment]
Actually, I was just asking if pure text could be obtained without code.
Well thank you :)
